services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  prestashop:
    image: prestashop/prestashop:9-apache
    platform: linux/amd64
    restart: always
    ports:
      - "8081:80"
    environment:
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWORD: admin
      PS_INSTALL_AUTO: "1"
      PS_LANGUAGE: ru
      PS_COUNTRY: RUS
      ADMIN_MAIL: admin@example.com
      ADMIN_PASSWD: Admin123!
      PS_FOLDER_ADMIN: administration
      PS_FOLDER_INSTALL: install
      PS_DOMAIN: localhost:8081
    volumes:
      - ps_data:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  prestashop_postinstall:
    image: alpine:3.19
    platform: linux/amd64
    depends_on:
      - prestashop
    volumes:
      - ps_data:/var/www/html
    restart: "no"
    command: >
      sh -lc '
        apk add --no-cache curl >/dev/null 2>&1 || true;
        echo "Waiting for PrestaShop HTTP to respond...";
        until curl -fsS http://prestashop/ >/dev/null; do sleep 5; done;
        echo "Waiting for config to exist...";
        until [ -f /var/www/html/config/settings.inc.php ] || [ -f /var/www/html/app/config/parameters.php ]; do sleep 2; done;
        echo "Removing install folders...";
        rm -rf /var/www/html/install /var/www/html/install-dev;
        echo "Clearing cache...";
        rm -rf /var/www/html/var/cache/* || true;
        echo "Done."
      '

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prestashop_tests
    working_dir: /my_test
    volumes:
      - .:/my_test
      - ps_data:/var/www/html

    environment:
      - DISPLAY=:99
      - PYTHONPATH=/my_test
    depends_on:
      - prestashop_postinstall
      - db
    command: ["pytest", "-v", "--headless"]

volumes:
  db_data:
  ps_data: